#!/bin/sh


if test "$#" -ne "2"
then
	echo "Falta un argumento"
	echo "$0 <ruta_origen> <ruta_destino>"
	exit 1
else
	if ! test -f "$1"
	then
		echo "El directorio no existe"
		exit 1
	else
		cp "$1" "$2"
		exit 0
	fi
fi
